site_name: SOFTDIGGER

theme:
  name: material
  language: ru
  logo: shovel.png
  flacticon: icon.png
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Темная тема
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Светлая тема

plugins:
  - search:
      lang:
      - ru
      - en

repo_url: https://github.com/Dancheg97/recourser
repo_name: SOFTDIGGER
edit_uri: ""

extra_css: 
  - extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences