site_name: SOFTDIGGER

repo_url: https://github.com/Dancheg97/recourser
repo_name: SOFTDIGGER
edit_uri: ""

extra_css: 
  - extra.css

plugins:
  - search:
      lang:
      - ru
      - en

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

theme:
  name: material
  language: ru
  logo: shovel.png
  favicon: favi.png
  features:
    - navigation.tabs
    # - navigation.expand
    - navigation.top
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Темная тема
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Светлая тема
